name: te_widgets
description: "Te Flutter Widgets"
version: 0.0.9

homepage: https://teranes10.github.io/flutter-libs
repository: https://github.com/teranes10/flutter-libs/tree/master/packages/te_widgets

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.1.2
  intl: ^0.20.2
  responsive_builder: ^0.7.1
  toastification: ^3.0.3
  pdf: ^3.11.3
  file_saver: ^0.3.1
  file_picker: ^10.3.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/no_image.png
    
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Light.ttf
          weight: 300
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
