import 'package:te_widgets/te_widgets.dart';

/// Helper utility for evaluating [TFilter] / [TFilterRule] / `advancedSearch`
/// conditions locally on in-memory objects and collections.
class TFilterEvaluator {
  /// Evaluates whether an [item] matches the given [advancedSearch] criteria map.
  ///
  /// The [advancedSearch] map is typically generated by [TFilterRule.rulesToJson]
  /// or filter models (e.g. `{'name': {'contains': 'abc'}, 'price': {'gte': 10}}`).
  ///
  /// [filterDefs] is an optional list of [TFilterDef] descriptors used to locate
  /// property getters and type information for each field key.
  static bool matches<T>(
    T item,
    Map<String, dynamic>? advancedSearch, [
    List<TFilterDef<T>>? filterDefs,
  ]) {
    if (advancedSearch == null || advancedSearch.isEmpty) return true;

    for (final entry in advancedSearch.entries) {
      final fieldKey = entry.key;
      final criteria = entry.value;

      if (criteria == null) continue;

      // Find matching definition if available (by exact key, case-insensitive, normalized, or dot path)
      final def = _findMatchingDef<T>(filterDefs, fieldKey);

      // If criteria is a nested property map (no operator keys), recurse on child object
      if (criteria is Map<String, dynamic> && !_isOperatorMap(criteria)) {
        final dynamic childItem = _extractFieldValue<T>(item, fieldKey, def);
        if (!_matchesNestedCriteria<T>(childItem, fieldKey, criteria, filterDefs)) {
          return false;
        }
        continue;
      }

      // Extract field value from item using getter, expression, or nested map/object path
      final dynamic itemVal = _extractFieldValue<T>(item, fieldKey, def);

      // Evaluate criteria against field value
      if (!_matchesCriteria(itemVal, criteria, def)) {
        return false;
      }
    }

    return true;
  }

  /// Evaluates whether an [item] matches a list of active [TFilterRule]s.
  static bool matchesRules<T>(
    T item,
    List<TFilterRule>? rules, [
    List<TFilterDef<T>>? filterDefs,
  ]) {
    if (rules == null || rules.isEmpty) return true;
    final jsonMap = TFilterRule.rulesToJson(rules, filterDefs ?? const []);
    return matches<T>(item, jsonMap, filterDefs);
  }

  /// Finds a matching [TFilterDef] using smart key matching (exact, case-insensitive, normalized, dot-path).
  static TFilterDef<T>? _findMatchingDef<T>(List<TFilterDef<T>>? filterDefs, String key) {
    if (filterDefs == null || filterDefs.isEmpty) return null;

    // 1. Exact key match
    for (final d in filterDefs) {
      if (d.key == key) return d;
    }

    // 2. Case-insensitive key match
    final lowerKey = key.toLowerCase();
    for (final d in filterDefs) {
      if (d.key.toLowerCase() == lowerKey) return d;
    }

    // 3. Normalized match (e.g. 'user.address.city' matching 'userAddressCity' or 'user_address_city')
    final norm = key.replaceAll(RegExp(r'[\s_\.\-]+'), '').toLowerCase();
    for (final d in filterDefs) {
      if (d.key.replaceAll(RegExp(r'[\s_\.\-]+'), '').toLowerCase() == norm) return d;
    }

    return null;
  }

  /// Checks if a map contains known filter operator keys.
  static bool _isOperatorMap(Map<String, dynamic> map) {
    const ops = {
      'isNull',
      'isNotNull',
      'eq',
      'ne',
      'contains',
      'startsWith',
      'endsWith',
      'gt',
      'gte',
      'lt',
      'lte',
      'in',
      'notIn',
    };
    return map.keys.any((k) => ops.contains(k));
  }

  /// Recursively matches a nested property map against an extracted child object.
  static bool _matchesNestedCriteria<T>(
    dynamic childItem,
    String parentKey,
    Map<String, dynamic> nestedCriteria,
    List<TFilterDef<T>>? filterDefs,
  ) {
    if (childItem == null) return false;

    for (final subEntry in nestedCriteria.entries) {
      final subKey = subEntry.key;
      final fullPath = '$parentKey.$subKey';
      final subCriteria = subEntry.value;

      final subDef = _findMatchingDef<T>(filterDefs, fullPath) ?? _findMatchingDef<T>(filterDefs, subKey);

      if (subCriteria is Map<String, dynamic> && !_isOperatorMap(subCriteria)) {
        final dynamic nextChild = _extractFieldValue<T>(childItem, subKey, subDef);
        if (!_matchesNestedCriteria<T>(nextChild, fullPath, subCriteria, filterDefs)) {
          return false;
        }
      } else {
        final dynamic val = _extractFieldValue<T>(childItem, subKey, subDef);
        if (!_matchesCriteria(val, subCriteria, subDef)) {
          return false;
        }
      }
    }

    return true;
  }

  /// Extracts the field value from [item] using [def.getter] expression, `Map` nested path, or object traversal.
  static dynamic _extractFieldValue<T>(dynamic item, String fieldKey, TFilterDef<T>? def) {
    if (item == null) return null;

    // 1. Direct getter / prop expression from definition
    if (def?.map != null) {
      try {
        return def!.map!(item);
      } catch (_) {}
    }

    // 2. Map direct or dot-path traversal
    if (item is Map) {
      return _resolveMapPath(item, fieldKey);
    }

    // 3. Arbitrary object with toJson / toMap serialization
    return _resolveObjectPath(item, fieldKey);
  }

  /// Resolves a potentially nested field key (e.g. 'user.address.city' or 'price') in a Map.
  static dynamic _resolveMapPath(Map map, String fieldKey) {
    if (map.containsKey(fieldKey)) return map[fieldKey];

    // Case-insensitive direct lookup
    for (final k in map.keys) {
      if (k.toString().toLowerCase() == fieldKey.toLowerCase()) {
        return map[k];
      }
    }

    // Nested dot path (e.g. 'user.address.city')
    if (fieldKey.contains('.')) {
      final parts = fieldKey.split('.');
      dynamic current = map;
      for (final part in parts) {
        if (current == null) return null;
        if (current is Map) {
          if (current.containsKey(part)) {
            current = current[part];
          } else {
            dynamic matchedVal;
            bool found = false;
            for (final k in current.keys) {
              if (k.toString().toLowerCase() == part.toLowerCase()) {
                matchedVal = current[k];
                found = true;
                break;
              }
            }
            if (found) {
              current = matchedVal;
            } else {
              return null;
            }
          }
        } else {
          return null;
        }
      }
      return current;
    }

    return null;
  }

  /// Resolves a field key or nested path on arbitrary objects via toJson / toMap.
  static dynamic _resolveObjectPath(dynamic obj, String fieldKey) {
    if (obj == null) return null;

    try {
      final dynamic map = (obj as dynamic).toJson();
      if (map is Map) {
        return _resolveMapPath(map, fieldKey);
      }
    } catch (_) {}

    try {
      final dynamic map = (obj as dynamic).toMap();
      if (map is Map) {
        return _resolveMapPath(map, fieldKey);
      }
    } catch (_) {}

    return null;
  }

  /// Evaluates a criteria object (either a map of operators or a direct scalar value).
  static bool _matchesCriteria(dynamic itemVal, dynamic criteria, TFilterDef? def) {
    if (criteria is Map<String, dynamic>) {
      if (criteria.isEmpty) return true;

      // 1. isNull check
      if (criteria.containsKey('isNull') && criteria['isNull'] != null) {
        final bool isNullCondition = criteria['isNull'] as bool;
        if (isNullCondition) {
          if (itemVal != null) return false;
        } else {
          if (itemVal == null) return false;
        }
      }

      // If itemVal is null and we didn't return above, non-null operator checks must fail
      if (itemVal == null) {
        // If the only condition was isNull and it passed, we are good; otherwise non-null ops fail.
        final otherKeys = criteria.keys.where((k) => k != 'isNull');
        if (otherKeys.isNotEmpty) return false;
        return true;
      }

      // 2. Equals / Not Equals
      if (criteria.containsKey('eq') && criteria['eq'] != null) {
        if (!_matchEq(itemVal, criteria['eq'], def)) return false;
      }
      if (criteria.containsKey('ne') && criteria['ne'] != null) {
        if (_matchEq(itemVal, criteria['ne'], def)) return false;
      }

      // 3. String pattern matches
      if (criteria.containsKey('contains') && criteria['contains'] != null) {
        if (!_matchContains(itemVal, criteria['contains'])) return false;
      }
      if (criteria.containsKey('startsWith') && criteria['startsWith'] != null) {
        if (!_matchStartsWith(itemVal, criteria['startsWith'])) return false;
      }
      if (criteria.containsKey('endsWith') && criteria['endsWith'] != null) {
        if (!_matchEndsWith(itemVal, criteria['endsWith'])) return false;
      }

      // 4. Numeric / Date comparisons
      if (criteria.containsKey('gt') && criteria['gt'] != null) {
        if (!_matchCompare(itemVal, criteria['gt'], (cmp) => cmp > 0)) return false;
      }
      if (criteria.containsKey('gte') && criteria['gte'] != null) {
        if (!_matchCompare(itemVal, criteria['gte'], (cmp) => cmp >= 0)) return false;
      }
      if (criteria.containsKey('lt') && criteria['lt'] != null) {
        if (!_matchCompare(itemVal, criteria['lt'], (cmp) => cmp < 0)) return false;
      }
      if (criteria.containsKey('lte') && criteria['lte'] != null) {
        if (!_matchCompare(itemVal, criteria['lte'], (cmp) => cmp <= 0)) return false;
      }

      // 5. In / Not In lists
      if (criteria.containsKey('in') && criteria['in'] != null) {
        final inList = criteria['in'] as List?;
        if (inList != null && inList.isNotEmpty) {
          final matched = inList.any((target) => _matchEq(itemVal, target, def));
          if (!matched) return false;
        }
      }
      if (criteria.containsKey('notIn') && criteria['notIn'] != null) {
        final notInList = criteria['notIn'] as List?;
        if (notInList != null && notInList.isNotEmpty) {
          final matched = notInList.any((target) => _matchEq(itemVal, target, def));
          if (matched) return false;
        }
      }

      return true;
    }

    // Direct scalar comparison fallback (e.g. criteria is string or number)
    return _matchEq(itemVal, criteria, def);
  }

  static bool _matchEq(dynamic itemVal, dynamic target, TFilterDef? def) {
    if (itemVal == null && target == null) return true;
    if (itemVal == null || target == null) return false;

    // Boolean equality
    if (itemVal is bool || target is bool) {
      final b1 = itemVal is bool ? itemVal : itemVal.toString().toLowerCase() == 'true';
      final b2 = target is bool ? target : target.toString().toLowerCase() == 'true';
      return b1 == b2;
    }

    // Number equality
    if (itemVal is num || target is num) {
      final n1 = itemVal is num ? itemVal : num.tryParse(itemVal.toString());
      final n2 = target is num ? target : num.tryParse(target.toString());
      if (n1 != null && n2 != null) {
        return n1 == n2;
      }
    }

    // DateTime equality
    if (itemVal is DateTime || target is DateTime) {
      final d1 = itemVal is DateTime ? itemVal : DateTime.tryParse(itemVal.toString());
      final d2 = target is DateTime ? target : DateTime.tryParse(target.toString());
      if (d1 != null && d2 != null) {
        if (def?.type == TFilterType.date || def?.formatType == TDateTimeFormatType.date) {
          return d1.year == d2.year && d1.month == d2.month && d1.day == d2.day;
        }
        return d1.isAtSameMomentAs(d2);
      }
    }

    // Enum equality
    if (itemVal is Enum) {
      final targetStr = target is Enum ? target.name : target.toString();
      return itemVal.name.toLowerCase() == targetStr.toLowerCase() || itemVal.toString().toLowerCase() == targetStr.toLowerCase();
    }

    // Case-insensitive string equality
    return itemVal.toString().toLowerCase() == target.toString().toLowerCase();
  }

  static bool _matchContains(dynamic itemVal, dynamic target) {
    if (itemVal == null || target == null) return false;
    return itemVal.toString().toLowerCase().contains(target.toString().toLowerCase());
  }

  static bool _matchStartsWith(dynamic itemVal, dynamic target) {
    if (itemVal == null || target == null) return false;
    return itemVal.toString().toLowerCase().startsWith(target.toString().toLowerCase());
  }

  static bool _matchEndsWith(dynamic itemVal, dynamic target) {
    if (itemVal == null || target == null) return false;
    return itemVal.toString().toLowerCase().endsWith(target.toString().toLowerCase());
  }

  static bool _matchCompare(dynamic itemVal, dynamic target, bool Function(int) predicate) {
    if (itemVal == null || target == null) return false;

    // Numbers
    if (itemVal is num || target is num) {
      final n1 = itemVal is num ? itemVal : num.tryParse(itemVal.toString());
      final n2 = target is num ? target : num.tryParse(target.toString());
      if (n1 != null && n2 != null) {
        return predicate(n1.compareTo(n2));
      }
    }

    // DateTime
    if (itemVal is DateTime || target is DateTime) {
      final d1 = itemVal is DateTime ? itemVal : DateTime.tryParse(itemVal.toString());
      final d2 = target is DateTime ? target : DateTime.tryParse(target.toString());
      if (d1 != null && d2 != null) {
        return predicate(d1.compareTo(d2));
      }
    }

    // Comparable fallback
    if (itemVal is Comparable && target is Comparable) {
      try {
        return predicate(itemVal.compareTo(target));
      } catch (_) {}
    }

    return false;
  }
}
